Work
CODERS-BAY/aufgabe-5-zoo-applikation-felix368 pull request #2
Opened 2023-08-03 14:44 UTC by felix368

Hallo,
ich konnte erst gestern mit dem Projekt angefangen, da ich im Urlaub war, daher ist es noch nicht sehr viel, es wär aber super, wenn du mal einen Blick draufwerfen könntest. Ich hatte etwas schwingenden mit der post API hatte vor allem wie ich auf den Body zugreifen kann, ich habe zwar eine Lösung gefunden, die ist allerdings nicht sehr elegant.
Ein weiterer Punkt wäre der Datenbank zugreifen, zurzeit baue ich für jedes Statement eine neue Verbindung auf, ist das ein Problem?

2023-08-08 09:10 UTC, x21L requested changes
Die DbConnection Klasse darf wirklich nur die DB Verbindung aufbauen. Dort sollen keine SQL Statements vorkommen. Die gehören alle in die Controller Klasse. Bei Bedarf kannst du gerne eine allgemeine Klasse als zb. Superklasse einführen und die Statements dort umsetzten. Die DB Verbindung kann als Singleton umgesetzt werden. Hier ein Beispiel: https://gist.github.com/jasoet/3843797

Check nochmals deine Methoden und Variablen, da sind einige Tippfehler drinnen.

Um nicht mit dem Body arbeiten zu müssen, kannst du gerne Parameter im Request verwenden. Grundsätzlich ist das mit dem Body aber so in Ordnung. Falls du es noch nicht gefunden hast, wäre hier noch etwas Doku dazu: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/use-http-context?view=aspnetcore-7.0

Verwende auch JSON für Serialisierung und Deserialisierung.

2023-08-08 09:10 UTC, x21L commented on Program.cs
> +        return totalPrice;
`return await KassiererController.InsertTicketInDb(body);`

2023-08-08 09:10 UTC, x21L commented on Program.cs
> +    return tickets;
return ...

2023-08-08 09:10 UTC, x21L commented on Program.cs
> +    return animals;
return...

2023-08-08 09:10 UTC, x21L commented on Program.cs
> +    return animals;
return

2023-08-08 09:10 UTC, x21L commented on Program.cs
> +    return animals;
return...

2023-08-08 09:10 UTC, x21L commented on controller/BesucherController.cs
> +        var animalvalues = new Dictionary<string,string>[animals.Count];
Default size --> great 😄

2023-08-08 09:10 UTC, x21L commented on controller/DBConnection.cs
> +﻿using Microsoft.VisualBasic;
why?

2023-08-08 09:10 UTC, x21L commented on controller/DBConnection.cs
> +    public static async Task NewSqlInsertCommand(String sqlCommand)
Use `string` not String.

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/

2023-08-08 09:10 UTC, x21L commented on controller/DBConnection.cs
> +                    }
Shorter with just using statement:

~~~csharp
await using var command = conn.CreateCommand();
command.CommandText = sqlCommand;


// execute statement in database 
await using var reader = await command.ExecuteReaderAsync();

while (await reader.ReadAsync())
{
  var currentAnimal = new Animal(reader.GetInt32(0), reader.GetString(1), 
  reader.GetString(2), reader.GetInt32(3));

  animals.Add(currentAnimal);

}
~~~

2023-08-08 09:10 UTC, x21L commented on controller/KassiererController.cs
> +        List<double> ticketPrices = new List<double>();
... = new();

2023-08-08 09:10 UTC, x21L commented on controller/KassiererController.cs
> +        return ticketPrices;
Searching in dictionaries can be done easier. But no problem, we did not do it yet.
https://learn.microsoft.com/en-us/answers/questions/1163910/how-to-search-dictionary-key-and-find-the-value-in

2023-08-08 09:10 UTC, x21L commented on model/Animal.cs
>      }
why? Use JSON as string in the ToString method for example.

2023-08-08 09:10 UTC, x21L commented on controller/KassiererController.cs
> +
Why?

2023-08-15 05:13 UTC, felix368 commented
Hallo Lukas @x21L , das Projekt ist soweit fertig, ich habe versucht dein Feedback so gut wie möglich einzubauen, den Umgang mit den dictionaries hab ich vorerst noch nicht geändert, da ich ihn zum Lesen recht angenehm finde. Die DBconnection hab ich komplett umgeschrieben und die stammen in SqlCommands klasse ausgelagert.
Ich bin mir aber sicher, dass man noch einiges besser machen kann, daher würde ich mich über dein Feedback freuen.

2023-08-21 06:44 UTC, merged

2023-08-21 07:25 UTC, Anderl1989 requested changes
Ich habe es derweil noch nicht getestet, nur mal den frontend code überprüft.

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/AnimalList.jsx
> +    console.log(value.value[0])
Ich empfehle bei Logs immer einen Kommentar dazu zu geben, wenn man eine Menge Logs hat, hilft das die Übersicht beizubehalten, welcher Log welcher ist. der console.log Methode kann man auch mehrere Parameter übergeben, die alle auf der Konsole ausgegeben werden. Also z.B.
```javascript
console.log('AnimalList value', value);
```

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/AnimalList.jsx
Die Datei sollte in den src-Ordner verschoben werden. Ich empfehle innerhalb des src-Ordners weitere Unterordner für Seiten (pages), die vom Router aufgerufen werden und Bausteine (components) für Komponenten die von Seiten oder anderen Komponenten verwendet werden.

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/AnimalList.jsx
> +export default function AnimalList(value) {
Bei React-Parametern nutzt man im allgemeinen Object-Destructuring, um später nicht `value.value` schreiben zu müssen, in diesem Beispiel wäre das dann
```javascript
export default function AnimalList({ value }) {
```
beachte die geschwungenen Klammern um den Parameter, damit wird aus dem übergebenen Objekt das Attribut `value` direkt extrahiert. Du brauchst dann bei der Verwendung nicht mehr `value.value` schreiben, sondern kannst `value` alleine verwenden. Ist in diesem Beispiel etwas verwirrend, weil bei dir sowohl das Objekt, als auch das Attribut im Objekt `value` heißen :D

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/AnimalList.jsx
> +                            key={row.name}
Beachte, dass der `key` eindeutig sein sollte. Da es auch eine `row.id` gibt, wäre die vermutliuch sinnvoller als `row.name`.

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/PflegerSelectDialog.jsx
Bitte ebenfalls in src-Ordner bzw. Unterordner davon verschieben

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/PflegerSelectDialog.jsx
> +export default function PlegerSelectDialog({animal,okClick,cancelClick}) {
Für Callback-Funktionen (meist eine Art Event-Listener) gibt es die Namenskonvention das Wort `on` davor zu schreiben. Ich würde die Funktionen hier z.B. `onSelect` und `onCancel` nennen. Beachte, dass du die Funktionsnamen dann auch bei Verwendung und dort wo die Komponente eingesetzt wird umändern musst.

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/PflegerSelectDialog.jsx
> +                        <TextField onChange={(e)=>{ setNewData(e.target.value)}} label="Neue Daten" variant="outlined" />
du solltest beim Text-Field noch das Attribut `value={newData}` hinzufügen, da es sonst vorkommen kann, dass nach einer anderen State-Änderung das Feld leer ist, obwohl etwas in `newData` gespeichert ist.

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/index.html
> +    <title>Vite + React</title>
Den Titlel solltest du ändern, dieser wird in der Tab-Bar des Browsers und beim setzen von Lesezeichen verwendet

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/public/vite.svg
Die Datei kann vermutlich gelöscht werden?

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/App.css
Ich nehme an, der Inhalt der Datei stammt noch von der Erstellung mit vite? Ich würde das reduzieren, auf das was wirklich benötigt wird

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/App.jsx
> +                <CategorCard   title={"TierPfleger"} imagePath={".\\lemurs.jpg"}/>
im Web sollten Pfade immer mit `/` statt `\` funktionieren, dann müsstest du das Zeichen nicht escapen. So kann es sogar mit Linux und Mac Probleme geben den Pfad aufzulösen

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/Besucher.jsx
> +            <TextField fullWidth onChange={(e)=>{ setAnimalName(e.target.value)}} label="Tier Name" id="fullWidth" />
Hier sollte wieder das `value` Attribut gesetzt werden

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/Kassierer.jsx
> +        return  await new Promise(async(resolve)=>{
warum brauchst du hier eine Instanz von Promise? die `buyTicket` Funktion ist eh schon async, du kannst also eh awaiten und `data` am Ende einfach returnen

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/Kassierer.jsx
> +            const data = response.json();
`response.json` ist asynchron und sollte awaited werden

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/Kassierer.jsx
> +            if(response.status==200){
du solltest den Status prüfen, bevor du das `responser.json()` aufrufst, da viele 404 Seiten HTML zurück geben, was nicht als JSON geparsed werden kann

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/Kassierer.jsx
> +    const [snackBar, setsnackBar] = useState(false);
Typo, es sollte `setSnackBar` heißen (mit großem S). muss auch bei Verwendung ausgebessert werden

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/Kassierer.jsx
> +        const finaldate =date.getFullYear() + '-' + (date.getMonth() <= 9 ? `0${date.getMonth()+1}` : date.getMonth()+1) + '-' + (date.getDate() <= 9 ? `0${date.getDate()}` : date.getDate())
Bei derart komplexen Zeilen empfehle ich Zeilenumbrüche, damit sie übersichtlich bleiben.
Man hätte dass aber auch deutlich einfacher schreiben können, z.B.
```javascript
const finalDate = date.toISOString().split('T')[0];
```
oder mithilfe einer Library (z.B. Luxon https://moment.github.io/luxon/index.html#/formatting )

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/Tierpfleger.jsx
> +        return ()=>{
die returnte Funktion nutzt in diesem Fall nichts, das würde nur innerhalb eines `useEffect` das gewünschte Ergebnis erzielen (das löschen des Timeouts, wenn die Komponente nicht mehr verwendet wird). Du müsstest diesen Teil also in ein `useEffect` auslagern

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/Tierpfleger.jsx
> +            <TextField fullWidth onChange={(e)=>{ setPflegerId(e.target.value)}} label="Pfleger ID" id="fullWidth" />
`value` Attribut setzen

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/Kassierer.jsx
> +        return ()=>{
die returnte Funktion nutzt in diesem Fall nichts, das würde nur innerhalb eines useEffect das gewünschte Ergebnis erzielen (das löschen des Timeouts, wenn die Komponente nicht mehr verwendet wird). Du müsstest diesen Teil also in ein useEffect auslagern

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/TicketList.jsx
> +export default function TicketList(value) {
Object Destructuring nutzen

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/Tierpfleger.jsx
> +        return (await data).json();
das `await` sollte bereits in der vorigen Zeile vor dem `fetch` stehen, dann kann man sich hier die Klammern sparen

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/Tierpfleger.jsx
> +        const data = await fetch(`http://localhost:5207/api/Tierpfleger/updateAnimal/${id}&${columnName}&${newData}`)
Der Request klingt als wolltest du am Server etwas updaten. Da sollte man die Standards einhalten und einen PUT-Request machen (das muss natürlich auch am Server eingestellt werden) (GET (default) = Daten vom Server holen, POST = Daten am Server erstellen, PUT = Daten updaten, DELETE = daten löschen).

2023-08-21 07:25 UTC, Anderl1989 commented on frontend/src/assets/react.svg
kann vermutlich gelöscht werden?